# TCL File Generated by Component Editor 18.1
# Fri Nov 06 22:21:41 CET 2020
# DO NOT MODIFY


# 
# AvalonRAMConnector_mono_1b "AvalonRAMConnector monochromatic 1b" v1.0
# Norbert Ligas (github.com/LigasN) 2020.11.06.22:21:41
# Connector between monochromatic 1b HDMIDriver and Avalon VRAM (2-port RAM).
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AvalonRAMConnector_mono_1b
# 
set_module_property DESCRIPTION "Connector between monochromatic 1b HDMIDriver and Avalon VRAM (2-port RAM)."
set_module_property NAME AvalonRAMConnector_mono_1b
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP HDMI/Connectors
set_module_property AUTHOR "Norbert Ligas (github.com/LigasN)"
set_module_property ICON_PATH ../../Assets/HDMI_mono_1b.jpg
set_module_property DISPLAY_NAME "AvalonRAMConnector monochromatic 1b"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AvalonRAMConnector
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AvalonRAMConnector.vhd VHDL PATH AvalonRAMConnector.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL AvalonRAMConnector
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AvalonRAMConnector.vhd VHDL PATH AvalonRAMConnector.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL AvalonRAMConnector
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AvalonRAMConnector.vhd VHDL PATH AvalonRAMConnector.vhd


# 
# parameters
# 
add_parameter DISPLAY_RES_WIDTH INTEGER 640
set_parameter_property DISPLAY_RES_WIDTH DEFAULT_VALUE 640
set_parameter_property DISPLAY_RES_WIDTH DISPLAY_NAME DISPLAY_RES_WIDTH
set_parameter_property DISPLAY_RES_WIDTH TYPE INTEGER
set_parameter_property DISPLAY_RES_WIDTH UNITS None
set_parameter_property DISPLAY_RES_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DISPLAY_RES_WIDTH HDL_PARAMETER true
add_parameter DISPLAY_RES_HEIGHT INTEGER 480
set_parameter_property DISPLAY_RES_HEIGHT DEFAULT_VALUE 480
set_parameter_property DISPLAY_RES_HEIGHT DISPLAY_NAME DISPLAY_RES_HEIGHT
set_parameter_property DISPLAY_RES_HEIGHT TYPE INTEGER
set_parameter_property DISPLAY_RES_HEIGHT UNITS None
set_parameter_property DISPLAY_RES_HEIGHT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DISPLAY_RES_HEIGHT HDL_PARAMETER true
add_parameter PX_X_SPLIT INTEGER 20
set_parameter_property PX_X_SPLIT DEFAULT_VALUE 20
set_parameter_property PX_X_SPLIT DISPLAY_NAME PX_X_SPLIT
set_parameter_property PX_X_SPLIT TYPE INTEGER
set_parameter_property PX_X_SPLIT UNITS None
set_parameter_property PX_X_SPLIT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PX_X_SPLIT HDL_PARAMETER true
add_parameter PX_Y_SPLIT INTEGER 20
set_parameter_property PX_Y_SPLIT DEFAULT_VALUE 20
set_parameter_property PX_Y_SPLIT DISPLAY_NAME PX_Y_SPLIT
set_parameter_property PX_Y_SPLIT TYPE INTEGER
set_parameter_property PX_Y_SPLIT UNITS None
set_parameter_property PX_Y_SPLIT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PX_Y_SPLIT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits WORDS
set_interface_property avalon_master associatedClock px_clk
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 1
set_interface_property avalon_master readWaitTime 0
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master address address Output 21
add_interface_port avalon_master read read Output 1
add_interface_port avalon_master readdata readdata Input 8
add_interface_port avalon_master write write Output 1
add_interface_port avalon_master writedata writedata Output 8


# 
# connection point px_clk
# 
add_interface px_clk clock end
set_interface_property px_clk clockRate 0
set_interface_property px_clk ENABLED true
set_interface_property px_clk EXPORT_OF ""
set_interface_property px_clk PORT_NAME_MAP ""
set_interface_property px_clk CMSIS_SVD_VARIABLES ""
set_interface_property px_clk SVD_ADDRESS_GROUP ""

add_interface_port px_clk px_clk clk Input 1


# 
# connection point px_address
# 
add_interface px_address conduit end
set_interface_property px_address associatedClock px_clk
set_interface_property px_address associatedReset ""
set_interface_property px_address ENABLED true
set_interface_property px_address EXPORT_OF ""
set_interface_property px_address PORT_NAME_MAP ""
set_interface_property px_address CMSIS_SVD_VARIABLES ""
set_interface_property px_address SVD_ADDRESS_GROUP ""

add_interface_port px_address px_x px_x Input 12
add_interface_port px_address px_y px_y Input 12


# 
# connection point px_color
# 
add_interface px_color conduit end
set_interface_property px_color associatedClock px_clk
set_interface_property px_color associatedReset ""
set_interface_property px_color ENABLED true
set_interface_property px_color EXPORT_OF ""
set_interface_property px_color PORT_NAME_MAP ""
set_interface_property px_color CMSIS_SVD_VARIABLES ""
set_interface_property px_color SVD_ADDRESS_GROUP ""

add_interface_port px_color px_color px_color Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock px_clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

