# TCL File Generated by Component Editor 18.1
# Tue Oct 06 23:23:32 CEST 2020
# DO NOT MODIFY


# 
# HDMI_IMAGE_GEN_MONO_1b "HDMI image generator monochromatic 1b" v1.0
# Norbert Ligas 2020.10.06.23:23:32
# Generates image for HDMI, which looks like screensaver
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module HDMI_IMAGE_GEN_MONO_1b
# 
set_module_property DESCRIPTION "Generates image for HDMI, which looks like screensaver"
set_module_property NAME HDMI_IMAGE_GEN_MONO_1b
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP HDMI/ImageGenerators
set_module_property AUTHOR "Norbert Ligas"
set_module_property ICON_PATH ../../Assets/HDMI_mono_1b.jpg
set_module_property DISPLAY_NAME "HDMI image generator monochromatic 1b"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL HDMIImageGenerator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file HDMIImageGenerator.vhd VHDL PATH HDMIImageGenerator.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL HDMIImageGenerator
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file HDMIImageGenerator.vhd VHDL PATH HDMIImageGenerator.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL HDMIImageGenerator
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file HDMIImageGenerator.vhd VHDL PATH HDMIImageGenerator.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point HDMIImageGenerator
# 
add_interface HDMIImageGenerator conduit end
set_interface_property HDMIImageGenerator associatedClock clock
set_interface_property HDMIImageGenerator associatedReset ""
set_interface_property HDMIImageGenerator ENABLED true
set_interface_property HDMIImageGenerator EXPORT_OF ""
set_interface_property HDMIImageGenerator PORT_NAME_MAP ""
set_interface_property HDMIImageGenerator CMSIS_SVD_VARIABLES ""
set_interface_property HDMIImageGenerator SVD_ADDRESS_GROUP ""

add_interface_port HDMIImageGenerator px_color px_color Output 1


# 
# connection point PX_ADDRESS
# 
add_interface PX_ADDRESS conduit end
set_interface_property PX_ADDRESS associatedClock clock
set_interface_property PX_ADDRESS associatedReset ""
set_interface_property PX_ADDRESS ENABLED true
set_interface_property PX_ADDRESS EXPORT_OF ""
set_interface_property PX_ADDRESS PORT_NAME_MAP ""
set_interface_property PX_ADDRESS CMSIS_SVD_VARIABLES ""
set_interface_property PX_ADDRESS SVD_ADDRESS_GROUP ""

add_interface_port PX_ADDRESS px_x px_x Input 13
add_interface_port PX_ADDRESS px_y px_y Input 13

