// PongFPGA_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module PongFPGA_mm_interconnect_0 (
		input  wire        PLL_c1_clk,                                                     //                                                   PLL_c1.clk
		input  wire        AvalonRAMConnector_mono_1b_0_reset_reset_bridge_in_reset_reset, // AvalonRAMConnector_mono_1b_0_reset_reset_bridge_in_reset.reset
		input  wire [20:0] AvalonRAMConnector_mono_1b_0_avalon_master_address,             //               AvalonRAMConnector_mono_1b_0_avalon_master.address
		input  wire        AvalonRAMConnector_mono_1b_0_avalon_master_read,                //                                                         .read
		output wire [7:0]  AvalonRAMConnector_mono_1b_0_avalon_master_readdata,            //                                                         .readdata
		input  wire        AvalonRAMConnector_mono_1b_0_avalon_master_write,               //                                                         .write
		input  wire [7:0]  AvalonRAMConnector_mono_1b_0_avalon_master_writedata,           //                                                         .writedata
		output wire [6:0]  VRAM_s2_address,                                                //                                                  VRAM_s2.address
		output wire        VRAM_s2_write,                                                  //                                                         .write
		input  wire [7:0]  VRAM_s2_readdata,                                               //                                                         .readdata
		output wire [7:0]  VRAM_s2_writedata,                                              //                                                         .writedata
		output wire        VRAM_s2_chipselect,                                             //                                                         .chipselect
		output wire        VRAM_s2_clken                                                   //                                                         .clken
	);

	wire         avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_waitrequest;   // VRAM_s2_translator:uav_waitrequest -> AvalonRAMConnector_mono_1b_0_avalon_master_translator:uav_waitrequest
	wire   [7:0] avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_readdata;      // VRAM_s2_translator:uav_readdata -> AvalonRAMConnector_mono_1b_0_avalon_master_translator:uav_readdata
	wire         avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_debugaccess;   // AvalonRAMConnector_mono_1b_0_avalon_master_translator:uav_debugaccess -> VRAM_s2_translator:uav_debugaccess
	wire  [20:0] avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_address;       // AvalonRAMConnector_mono_1b_0_avalon_master_translator:uav_address -> VRAM_s2_translator:uav_address
	wire         avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_read;          // AvalonRAMConnector_mono_1b_0_avalon_master_translator:uav_read -> VRAM_s2_translator:uav_read
	wire   [0:0] avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_byteenable;    // AvalonRAMConnector_mono_1b_0_avalon_master_translator:uav_byteenable -> VRAM_s2_translator:uav_byteenable
	wire         avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_readdatavalid; // VRAM_s2_translator:uav_readdatavalid -> AvalonRAMConnector_mono_1b_0_avalon_master_translator:uav_readdatavalid
	wire         avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_lock;          // AvalonRAMConnector_mono_1b_0_avalon_master_translator:uav_lock -> VRAM_s2_translator:uav_lock
	wire         avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_write;         // AvalonRAMConnector_mono_1b_0_avalon_master_translator:uav_write -> VRAM_s2_translator:uav_write
	wire   [7:0] avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_writedata;     // AvalonRAMConnector_mono_1b_0_avalon_master_translator:uav_writedata -> VRAM_s2_translator:uav_writedata
	wire   [0:0] avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_burstcount;    // AvalonRAMConnector_mono_1b_0_avalon_master_translator:uav_burstcount -> VRAM_s2_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (21),
		.AV_DATA_W                   (8),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (1),
		.UAV_ADDRESS_W               (21),
		.UAV_BURSTCOUNT_W            (1),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (0),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (1),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) avalonramconnector_mono_1b_0_avalon_master_translator (
		.clk                    (PLL_c1_clk),                                                                                    //                       clk.clk
		.reset                  (AvalonRAMConnector_mono_1b_0_reset_reset_bridge_in_reset_reset),                                //                     reset.reset
		.uav_address            (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (AvalonRAMConnector_mono_1b_0_avalon_master_address),                                            //      avalon_anti_master_0.address
		.av_read                (AvalonRAMConnector_mono_1b_0_avalon_master_read),                                               //                          .read
		.av_readdata            (AvalonRAMConnector_mono_1b_0_avalon_master_readdata),                                           //                          .readdata
		.av_write               (AvalonRAMConnector_mono_1b_0_avalon_master_write),                                              //                          .write
		.av_writedata           (AvalonRAMConnector_mono_1b_0_avalon_master_writedata),                                          //                          .writedata
		.av_waitrequest         (),                                                                                              //               (terminated)
		.av_burstcount          (1'b1),                                                                                          //               (terminated)
		.av_byteenable          (1'b1),                                                                                          //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                                          //               (terminated)
		.av_begintransfer       (1'b0),                                                                                          //               (terminated)
		.av_chipselect          (1'b0),                                                                                          //               (terminated)
		.av_readdatavalid       (),                                                                                              //               (terminated)
		.av_lock                (1'b0),                                                                                          //               (terminated)
		.av_debugaccess         (1'b0),                                                                                          //               (terminated)
		.uav_clken              (),                                                                                              //               (terminated)
		.av_clken               (1'b1),                                                                                          //               (terminated)
		.uav_response           (2'b00),                                                                                         //               (terminated)
		.av_response            (),                                                                                              //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                          //               (terminated)
		.av_writeresponsevalid  ()                                                                                               //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (7),
		.AV_DATA_W                      (8),
		.UAV_DATA_W                     (8),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (1),
		.UAV_ADDRESS_W                  (21),
		.UAV_BURSTCOUNT_W               (1),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (1),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) vram_s2_translator (
		.clk                    (PLL_c1_clk),                                                                                    //                      clk.clk
		.reset                  (AvalonRAMConnector_mono_1b_0_reset_reset_bridge_in_reset_reset),                                //                    reset.reset
		.uav_address            (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (avalonramconnector_mono_1b_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (VRAM_s2_address),                                                                               //      avalon_anti_slave_0.address
		.av_write               (VRAM_s2_write),                                                                                 //                         .write
		.av_readdata            (VRAM_s2_readdata),                                                                              //                         .readdata
		.av_writedata           (VRAM_s2_writedata),                                                                             //                         .writedata
		.av_chipselect          (VRAM_s2_chipselect),                                                                            //                         .chipselect
		.av_clken               (VRAM_s2_clken),                                                                                 //                         .clken
		.av_read                (),                                                                                              //              (terminated)
		.av_begintransfer       (),                                                                                              //              (terminated)
		.av_beginbursttransfer  (),                                                                                              //              (terminated)
		.av_burstcount          (),                                                                                              //              (terminated)
		.av_byteenable          (),                                                                                              //              (terminated)
		.av_readdatavalid       (1'b0),                                                                                          //              (terminated)
		.av_waitrequest         (1'b0),                                                                                          //              (terminated)
		.av_writebyteenable     (),                                                                                              //              (terminated)
		.av_lock                (),                                                                                              //              (terminated)
		.uav_clken              (1'b0),                                                                                          //              (terminated)
		.av_debugaccess         (),                                                                                              //              (terminated)
		.av_outputenable        (),                                                                                              //              (terminated)
		.uav_response           (),                                                                                              //              (terminated)
		.av_response            (2'b00),                                                                                         //              (terminated)
		.uav_writeresponsevalid (),                                                                                              //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                                           //              (terminated)
	);

endmodule
